data:
  train_lmdb_dir: '/disk3/yxdong/Dcase2023/synth_real_data/synth_real_data_ACS/lmdb_foa_dev_ACSdata_label_len10s'
  test_lmdb_dir: '/disk3/yxdong/Dcase2023/synth_real_data/combine_synth_real/lmdb_test_foa_dev_data_label_len10s'
  ref_files_dir: '/disk3/yxdong/cache_aware_streaming_SELD_old/dataset/metadata_dev_test'
  norm_file: '/disk3/yxdong/cache_aware_streaming_SELD_old/dataset/24h_ACS_foa_wts'
  segment_len: 100
  select_num: 10  # video per seconds
  batch_size: 32
  train_ignore: 'enh' # No ACS
  test_ignore: 'enh'

model:
  type: 'finetune_seddoa_nopool_att_loss_last_layer'
  in_channel: 7
  in_dim: 64
  out_dim: 39
  att_context_size: [100,4]
  num_conformer_layer: 8
  encoder_dim: 256
  pre-train: True
  pre-train_model_t: 'test_models/RC_24h_Offline.pth'
  pre-train_model_s: 'test_models/RC_24h_Chunk[100,4]_8Conformer_Best.pth'

train:
  train_num_workers: 8
  test_num_workers: 4
  lr: 0.0004
  kl_gamma: [1, 0.5]
  nb_steps: 60000
  use_ts_distill: false
  use_hidden_distill: false  # 是否使用隐藏层蒸馏
  use_attn_distill: true    # 是否使用注意力图蒸馏
  att_distill_weighted: True
  attn_distill_layer_weight: [0, 0, 0, 0, 0, 0, 0, 1]
  ts_loss_weight: 0.5
  hidden_loss_weight: 0.0001   # 隐藏层损失权重
  attn_loss_weight: 2.0    # 注意力图损失权重

result:
  log_output_path: 'results/Finetune_T0.40_Cache_RC_24h_Chunk[100,4]_8ConformerLayer_att_loss_last_layer3/train.log'
  log_interval: 100
  checkpoint_output_dir: 'results/Finetune_T0.40_Cache_RC_24h_Chunk[100,4]_8ConformerLayer_att_loss_last_layer3/checkpoints'
  dcase_output_dir: 'results/Finetune_T0.40_Cache_RC_24h_Chunk[100,4]_8ConformerLayer_att_loss_last_layer3/results'


