data:
  train_lmdb_dir: '/disk6/yxdong/Dcase2023/synth_real_data/combine_synth_real/lmdb_foa_dev_data_label_len10s'
  test_lmdb_dir: '/disk6/yxdong/Dcase2023/synth_real_data/combine_synth_real/lmdb_test_foa_dev_data_label_len10s'
  ref_files_dir: 'dataset/metadata_dev_test'
  norm_file: 'dataset/24h_ACS_foa_wts'
  segment_len: 100
  batch_size: 16
  train_ignore: 'enh' # No ACS
  test_ignore: 'enh'

model:
  type: 'seddoa_nopool_APC'
  in_channel: 7
  in_dim: 64
  out_dim: 39
  num_conformer_layer: 8
  encoder_dim: 256
  cpc_future_steps: 10
  negative_samples: 10
  pre-train: False
  pre-train_model: '...'

train:
  train_num_workers: 8
  test_num_workers: 4
  lr: 0.001
  nb_steps: 120000
  early_stop_patience: 40
  cpc_loss_weight: 0.05

result:
  log_output_path: 'results/Offline_RC_24h_8ConformerLayer_CPC_fusteps_10_negsam_10/train.log'
  log_interval: 100
  checkpoint_output_dir: 'results/Offline_RC_24h_8ConformerLayer_CPC_fusteps_10_negsam_10/checkpoints'
  dcase_output_dir: 'results/Offline_RC_24h_8ConformerLayer_CPC_fusteps_10_negsam_10/results'


