data:
  ref_files_dir: 'dataset/metadata_dev_test'
  norm_file: 'dataset/24h_ACS_foa_wts'
  wav_path: 'dataset/foa_dev_test'

model:
  type: 'seddoa_nopool'
  in_channel: 7
  in_dim: 64
  out_dim: 39
  use_class_thre: False
  class_thre: [0.7, 0.7, 0.7, 0.45, 0.6, 0.3, 0.65, 0.55, 0.65, 0.7, 0.3, 0.7, 0.7]
  inf_type: 'past_future' # ave or past_future
  window_length: 1  # 每次处理的窗长/s
  segment_length: 5 # 每次音频段的长度
  output_num_frame: 10 # 每秒输出的帧数
  sr: 24000
  pre-train: True
  pre-train_model: 'results/Offline_RC_24h_8ConformerLayer_5s/checkpoints/checkpoint_epoch97_step52865.pth'

result:
  log_output_path: 'results/Test_RC_24h_Offline_8ConformerLayer_Buffered_2_P4F1/train.log'
  log_interval: 100
  dcase_output_dir: 'results/Test_RC_24h_Offline_8ConformerLayer_Buffered_2_P4F1/results'


